---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-datadog
  labels:
    project: prometheus-datadog
    role: prometheus-datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      project: prometheus-datadog
      role: prometheus-datadog
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: prometheus-datadog-server
      labels:
        project: prometheus-datadog
        role: prometheus-datadog
    spec:
      containers:
      - name: prometheus-datadog
        image: docker-registry.zende.sk/prometheus_datadog:latest
        resources:
          limits:
            cpu: 20m
            memory: 75Mi
        ports:
        - name: main-port
          containerPort: 4242
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 4242
          initialDelaySeconds: 30
          timeoutSeconds: 2
          failureThreshold: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-datadog
  labels:
    project: prometheus-datadog
    role: prometheus-datadog
    consulTags: serviceproxy-enabled
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: main-port
  selector:
    project: prometheus-datadog
    role: prometheus-datadog
